<div class="page-title">
    <h1>
        <?php echo $this->getTitle(); ?>
        <a href="<?php echo Mage::helper('super_payments/transaction')->generateOrderViewUrl($this->getOrder()->getId()); ?>" class="btn btn-redirect btn-sm"><span class="glyphicon glyphicon-share"></span><?php echo $this->__('Podgląd zamówienia'); ?></a>
    </h1>
</div>
<?php echo $this->getChildHtml('super_payments.transaction_form'); ?>
<?php echo $this->getChildHtml('super_payments.transaction_list'); ?>